#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

def configure(conf):
	conf.load('compiler_cxx')

def build(bld):
    library_files = bld.path.ant_glob("src/*.cpp")
    bld.stlib(target='rocmdrlib', source=library_files, includes=['./inc/'])
