#! /usr/bin/env python
# encoding: utf-8
# Mattias Frånberg, 2011
# 
# Root configuration file for the waf build system.
#

##
# Build the rocmdr program.
#
conf.find_program('gengetopt', var='GENGETOPT')
bld(
    rule='${GENGETOPT} -i ${SRC} -u',
    target="cmdline.h cmdline.c",
    source="rocmdr.ggo")

bld.program(source='rocmdr.cpp cmdline.c',
            target='rocmdr',
            use='rocmdrlib libcsv')
