#! /usr/bin/env python
# encoding: utf-8
# Mattias Frånberg, 2011
# 
# Root configuration file for the waf build system.
#

##
# Build the rocmdr program.
#
conf.find_program('gengetopt', var='GENGETOPT')
bld(
    rule='${GENGETOPT} -i ${SRC} -u --output-dir=%s' % ( bld.path.get_src( ).abspath( ) ),
    target="cmdline.h cmdline.c",
    source="rocmdr_snp.ggo")

bld.program(source='rocmdr_snp.cpp cmdline.c plink/PlinkIo.cpp',
            target='rocmdr_snp',
            includes='.',
            use='rocmdrlib libcsv plinkio')
