#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

library_files = bld.path.ant_glob("cxxtest/*.cpp")
bld.stlib(target='cxxtest', source=library_files, includes='.', export_includes='.')
