/*
 * RocMdrVisitor.h
 *
 *  Created on: Sep 3, 2012
 *      Author: fmattias
 */

#ifndef ROCMDRVISITOR_H_
#define ROCMDRVISITOR_H_

#include <vector>

#include <RocMdrResult.h>
#include <iter/InteractionIterator.h>
#include <stat/NullInteraction.h>
#include <data/PhenotypeMapping.h>

/**
 * This class responsibility is to compute and store
 * the RocMdr AUC for each interaction pair that
 * it visits.
 */
class RocMdrVisitor
: public InteractionIterator::InteractionVisitor
{
public:
	/**
	 * Constructor.
	 */
	RocMdrVisitor();

	/**
	 * This visitor computes the RocMdr AUC score for
	 * each interaction pair, and stores it in a
	 * RocMdrResult object.
	 *
	 * @see InteractionIterator::InteractionVisitor::visit.
	 */
	virtual void visit(ColumnData<unsigned char> &snps, std::vector<unsigned int> &indices, PhenotypeMapping &phenotypes);

	/**
	 * Returns the results.
	 *
	 * @return the results.
	 */
	std::vector<RocMdrResult> getResults();

private:
	/**
	 * P-value simulation.
	 */
	NullInteraction m_nullSimulator;

	/**
	 * List of results generated by the visits.
	 */
	std::vector<RocMdrResult> m_results;

};

#endif /* ROCMDRVISITOR_H_ */
