/*
 * RocMdrRestrictedBatch.h
 *
 *  Created on: Feb 27, 2012
 *      Author: fmattias
 */

#ifndef ROCMDRRESTRICTEDBATCH_H_
#define ROCMDRRESTRICTEDBATCH_H_

#include <set>
#include <vector>

#include <Filter.h>
#include <RocMdrResult.h>
#include <RecursionState.h>
#include <stat/NullInteraction.h>

class RocMdrRestrictedBatch
: public RocMdrBatch
{
public:
	/**
	 * Constructor.
	 *
	 * @param order Number of SNPs considered jointly from the
	 *              restricted set
	 */
	RocMdrRestrictedBatch(ColumnData<unsigned char> snps, PhenotypeMapping phenotypes, const std::vector<unsigned int> &restricted);

	/**
	 * Recursively computes the AUC for all possible
	 * tables of the given interaction order where each interaction
	 * is restricted contain one of the SNPs in the restricted set.
	 *
	 * @param interactionOrder Number of SNPs in each interaction for
	 *                         the restricted set.
	 *                         1 = One snp from the restricted set, together
	 *                             with one from the others.
	 *                         2 = Pairs from the restricted set, together
	 *                             with one from the others.
	 *
	 * @return List of results that contains the AUC for each table
	 *         of the given order.
	 */
	std::vector<RocMdrResult> run(unsigned int interactionOrder);

private:
	/**
	 * Recursively computes the AUC for all possible
	 * tables of the given order. At each recursive
	 * level a new locus is added, and when we are at
	 * the bottom of the recursion the AUC is computed.
	 *
	 * @param state Current state generated by the recursion.
	 * @param snps All snps.
	 * @param phenotypes Disease status of the individuals.
	 * @param results The list of results that will be produced.
	 */
	void
	runRocMdrRecursive(RecursionState &state,
					   std::vector<RocMdrResult> *results);

	/**
	 * All RocMdr analysis will always include at least one
	 * snp from this set.
	 */
	std::vector<unsigned int> m_restricted;

};

#endif /* ROCMDRRESTRICTEDBATCH_H_ */
