/*
 * RocMdrRestrictedBatch.h
 *
 *  Created on: Feb 27, 2012
 *      Author: fmattias
 */

#ifndef ROCMDRRESTRICTEDBATCH_H_
#define ROCMDRRESTRICTEDBATCH_H_

#include <set>
#include <vector>

#include <RocMdrResult.h>
#include <RecursionState.h>
#include <stat/NoAssociationSimulator.h>

class RocMdrRestrictedBatch
{
public:
	/**
	 * Constructor.
	 *
	 * @param order Number of SNPs considered jointly from the
	 *              restricted set
	 */
	RocMdrRestrictedBatch(unsigned int order);

	/**
	 * Sets the number of SNPs that are considered
	 * jointly against the phenotype from the restricted
	 * set. Each test is performed on one SNP from
	 * all the SNPs and order SNPs from the restricted set.
	 *
	 * @param order Number of SNPs considered jointly from the
	 *              restricted set. 1 is single SNP association, 2
	 *              is pairwise etc.
	 */
	void setOrder(unsigned int order);

	/**
	 * Recursively computes the AUC for all possible
	 * tables of the given interaction order where each interaction
	 * is restricted contain one of the SNPs in the restrict set.
	 *
	 * @param restricted List of restricted SNPs.
	 * @param snps All SNPs such that each column contains the SNPs for
	 *             a single loci.
	 * @param phenotypes Disease status of the individuals.
	 *
	 * @return List of results that contains the AUC for each table
	 *         of the given order.
	 */
	std::vector<RocMdrResult> run(std::vector<unsigned int> restricted,
								  ColumnData<unsigned char> snps,
								  PhenotypeMapping phenotypes);

private:
	/**
	 * Recursively computes the AUC for all possible
	 * tables of the given order. At each recursive
	 * level a new locus is added, and when we are at
	 * the bottom of the recursion the AUC is computed.
	 *
	 * @param state Current state generated by the recursion.
	 * @param restricted The restricted set of SNPs.
	 * @param snps All snps.
	 * @param phenotypes Disease status of the individuals.
	 * @param results The list of results that will be produced.
	 */
	void
	runRocMdrRecursive(RecursionState &state,
					   std::vector<unsigned int> &restricted,
					   ColumnData<unsigned char> &snps,
					   PhenotypeMapping &phenotypes,
					   std::vector<RocMdrResult> *results);

	/**
	 * Number of SNPs considered jointly from the restricted set.
	 */
	unsigned int m_order;

	/**
	 * Simulates the AUC under the null hypothesis.
	 */
	NoAssociationSimulator m_nullSimulator;
};

#endif /* ROCMDRRESTRICTEDBATCH_H_ */
