library( methods )

##
# This file contains S4 classes for running rocmdr over multiple iterations
# when varying some parameter.
#
#

##
# A class that calls rocmdr with the given files.
# 
# This constructor generates temporary file locations 
# for the input and output files.
# 
# @param rocmdr.path The path to the rocmdr binary.
#
RocMdrCall = function(rocmdr.path)
{
    new( "RocMdrCall", rocmdr.path )
}
setClass( "RocMdrCall",
          representation( rocmdr.path = "character",
                          input = "list",
                          result = "character" )
          )

setMethod( "initialize", "RocMdrCall", function(.Object, rocmdr.path) {
    .Object@rocmdr.path = rocmdr.path
    
    tmpDir = Sys.getenv( "TMPDIR" )
    .Object@input$factor = file.path( tmpDir, "factor.txt" )
    .Object@input$snp = file.path( tmpDir, "snp.txt" )
    .Object@input$phenotype = file.path( tmpDir, "phenotype.txt" )
    .Object@result = file.path( tmpDir, "res.txt" )
    
    .Object
})

runMdr.RocMdrCall = function(.Object)
{
    rocmdr.input = paste( .Object@input$snp, .Object@input$factor, .Object@input$phenotype )
    rocmdr.call = paste( .Object@rocmdr.path, rocmdr.input )        

    system( paste( rocmdr.call, ">", .Object@result ) )
}
setGeneric( "runMdr", function(.Object) standardGeneric("runMdr") );
setMethod( "runMdr",
           signature = signature( .Object = "RocMdrCall" ),
           runMdr.RocMdrCall
           )

##
# This class represents a set of rocmdr calls.
#
#
RocMdrBatch = function(rocmdr.path, numIterations)
{
    new( "RocMdrBatch", rocmdr.path, numIterations )
}

setClass( "RocMdrBatch",
          representation( rocMdrCall = "RocMdrCall",
                          numIterations = "numeric" )
          )

setMethod( "initialize", "RocMdrBatch", function(.Object, rocmdr.path, numIterations) {
    .Object@rocMdrCall = RocMdrCall( rocmdr.path )
    .Object@numIterations = numIterations
    
    .Object
})

##
# This method allowss you to run a series of rocmdr calls. The data for each call
# is generated by the 'generate' function, and the results over all iterations are
# supplied to the reduce function.
#
# @param .Object A RocMdrBatch object.
# @param paramList A column containing the parameter to vary
# @param generate A function that generates the data before each rocmdr call.
# @param reduce A function that takes the output from rocmdr.
# @param reduceData Object where reduce can store its data, this will be returned
#                   at the end.
#
# @return The reduceData object.
#
runBatch.RocMdrBatch = function(.Object, paramList, generate, reduce, reduceData)
{
    for( param in paramList )
    {
        resultList = list( )
        for( iteration in 1:numIterations )
        {
            print( paste( "Param:", param, "Iteration:", iteration ) )
            
            generate( param, .Object@rocMdrCall@input )
    
            runMdr( .Object@rocMdrCall )
    
            resultList[[ iteration ]] = read.table( .Object@rocMdrCall@result, header = TRUE )
        }
        reduceData = reduce( param, resultList, reduceData )
    }
    
    return( reduceData )
}
setGeneric( "runBatch", function(.Object, paramList, generate, reduce, reduceData) standardGeneric( "runBatch" ) );
setMethod( "runBatch",
           signature = signature( .Object = "RocMdrBatch",
                                  paramList = "numeric",
                                  generate = "function",
                                  reduce = "function",
                                  reduceData = "ANY" ),
           runBatch.RocMdrBatch
           )
