#! /usr/bin/env python
# encoding: utf-8
# Mattias Frånberg, 2011

# Declare name and version of the application
VERSION='0.0.1'
APPNAME='rocmdr'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')

def build(bld):
    bld.recurse("rocmdrlib")
    bld.program(source='rocmdr.cpp',
	            target='rocmdr',
	            use='rocmdrlib',
	            includes='rocmdrlib/inc/')

